name: Quality Assurance CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  qa:
    name: Quality Assurance CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          enable-uv-cache: true
          sync-uv: true

      - name: Format code
        run: uv run ruff format --diff

      - name: Lint code
        run: uv run ruff check

      - name: Type check
        run: uv run mypy

      - name: Run tests
        run: uv run python -m unittest

      - name: Build package
        run: uv build

      - name: Build docs
        run: uv run mkdocs build
